spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot
    username: postgres
    password: P@$$w0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop best for development recommended option is 'update'

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect